# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-14 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='common_detail',
            name='county',
            field=models.CharField(default=datetime.datetime(2018, 3, 14, 9, 35, 6, 787803, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
